ALTER TABLE correction_requests
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN edit_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE corrections
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN edit_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE study_sessions
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN deleted_at TIMESTAMPTZ;

ALTER TABLE study_cards
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN edit_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE learner_attempts
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN deleted_at TIMESTAMPTZ;
